// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package rpoboxconfigurator.proxies;

public class Box
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject boxMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "RPOBoxConfigurator.Box";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Sequence("Sequence"),
		Number("Number"),
		BoxStatus("BoxStatus"),
		NeighbourhoodMail("NeighbourhoodMail"),
		NumberString("NumberString"),
		IsNumberValid("IsNumberValid"),
		Box_Row("RPOBoxConfigurator.Box_Row"),
		Box_Wall__Selected("RPOBoxConfigurator.Box_Wall__Selected"),
		WallView_Box__Selected("RPOBoxConfigurator.WallView_Box__Selected");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Box(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "RPOBoxConfigurator.Box"));
	}

	protected Box(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject boxMendixObject)
	{
		if (boxMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("RPOBoxConfigurator.Box", boxMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a RPOBoxConfigurator.Box");

		this.boxMendixObject = boxMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Box.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static rpoboxconfigurator.proxies.Box initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return rpoboxconfigurator.proxies.Box.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static rpoboxconfigurator.proxies.Box initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new rpoboxconfigurator.proxies.Box(context, mendixObject);
	}

	public static rpoboxconfigurator.proxies.Box load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return rpoboxconfigurator.proxies.Box.initialize(context, mendixObject);
	}

	public static java.util.List<rpoboxconfigurator.proxies.Box> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<rpoboxconfigurator.proxies.Box> result = new java.util.ArrayList<rpoboxconfigurator.proxies.Box>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//RPOBoxConfigurator.Box" + xpathConstraint))
			result.add(rpoboxconfigurator.proxies.Box.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Sequence
	 */
	public final java.lang.Integer getSequence()
	{
		return getSequence(getContext());
	}

	/**
	 * @param context
	 * @return value of Sequence
	 */
	public final java.lang.Integer getSequence(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Sequence.toString());
	}

	/**
	 * Set value of Sequence
	 * @param sequence
	 */
	public final void setSequence(java.lang.Integer sequence)
	{
		setSequence(getContext(), sequence);
	}

	/**
	 * Set value of Sequence
	 * @param context
	 * @param sequence
	 */
	public final void setSequence(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer sequence)
	{
		getMendixObject().setValue(context, MemberNames.Sequence.toString(), sequence);
	}

	/**
	 * @return value of Number
	 */
	public final java.lang.Integer getNumber()
	{
		return getNumber(getContext());
	}

	/**
	 * @param context
	 * @return value of Number
	 */
	public final java.lang.Integer getNumber(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Number.toString());
	}

	/**
	 * Set value of Number
	 * @param number
	 */
	public final void setNumber(java.lang.Integer number)
	{
		setNumber(getContext(), number);
	}

	/**
	 * Set value of Number
	 * @param context
	 * @param number
	 */
	public final void setNumber(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer number)
	{
		getMendixObject().setValue(context, MemberNames.Number.toString(), number);
	}

	/**
	 * Set value of BoxStatus
	 * @param boxstatus
	 */
	public final rpoboxconfigurator.proxies.Status getBoxStatus()
	{
		return getBoxStatus(getContext());
	}

	/**
	 * @param context
	 * @return value of BoxStatus
	 */
	public final rpoboxconfigurator.proxies.Status getBoxStatus(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.BoxStatus.toString());
		if (obj == null)
			return null;

		return rpoboxconfigurator.proxies.Status.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of BoxStatus
	 * @param boxstatus
	 */
	public final void setBoxStatus(rpoboxconfigurator.proxies.Status boxstatus)
	{
		setBoxStatus(getContext(), boxstatus);
	}

	/**
	 * Set value of BoxStatus
	 * @param context
	 * @param boxstatus
	 */
	public final void setBoxStatus(com.mendix.systemwideinterfaces.core.IContext context, rpoboxconfigurator.proxies.Status boxstatus)
	{
		if (boxstatus != null)
			getMendixObject().setValue(context, MemberNames.BoxStatus.toString(), boxstatus.toString());
		else
			getMendixObject().setValue(context, MemberNames.BoxStatus.toString(), null);
	}

	/**
	 * Set value of NeighbourhoodMail
	 * @param neighbourhoodmail
	 */
	public final rpoboxconfigurator.proxies.NeighbourhoodMail getNeighbourhoodMail()
	{
		return getNeighbourhoodMail(getContext());
	}

	/**
	 * @param context
	 * @return value of NeighbourhoodMail
	 */
	public final rpoboxconfigurator.proxies.NeighbourhoodMail getNeighbourhoodMail(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.NeighbourhoodMail.toString());
		if (obj == null)
			return null;

		return rpoboxconfigurator.proxies.NeighbourhoodMail.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of NeighbourhoodMail
	 * @param neighbourhoodmail
	 */
	public final void setNeighbourhoodMail(rpoboxconfigurator.proxies.NeighbourhoodMail neighbourhoodmail)
	{
		setNeighbourhoodMail(getContext(), neighbourhoodmail);
	}

	/**
	 * Set value of NeighbourhoodMail
	 * @param context
	 * @param neighbourhoodmail
	 */
	public final void setNeighbourhoodMail(com.mendix.systemwideinterfaces.core.IContext context, rpoboxconfigurator.proxies.NeighbourhoodMail neighbourhoodmail)
	{
		if (neighbourhoodmail != null)
			getMendixObject().setValue(context, MemberNames.NeighbourhoodMail.toString(), neighbourhoodmail.toString());
		else
			getMendixObject().setValue(context, MemberNames.NeighbourhoodMail.toString(), null);
	}

	/**
	 * @return value of NumberString
	 */
	public final java.lang.String getNumberString()
	{
		return getNumberString(getContext());
	}

	/**
	 * @param context
	 * @return value of NumberString
	 */
	public final java.lang.String getNumberString(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.NumberString.toString());
	}

	/**
	 * Set value of NumberString
	 * @param numberstring
	 */
	public final void setNumberString(java.lang.String numberstring)
	{
		setNumberString(getContext(), numberstring);
	}

	/**
	 * Set value of NumberString
	 * @param context
	 * @param numberstring
	 */
	public final void setNumberString(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String numberstring)
	{
		getMendixObject().setValue(context, MemberNames.NumberString.toString(), numberstring);
	}

	/**
	 * @return value of IsNumberValid
	 */
	public final java.lang.Boolean getIsNumberValid()
	{
		return getIsNumberValid(getContext());
	}

	/**
	 * @param context
	 * @return value of IsNumberValid
	 */
	public final java.lang.Boolean getIsNumberValid(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.IsNumberValid.toString());
	}

	/**
	 * Set value of IsNumberValid
	 * @param isnumbervalid
	 */
	public final void setIsNumberValid(java.lang.Boolean isnumbervalid)
	{
		setIsNumberValid(getContext(), isnumbervalid);
	}

	/**
	 * Set value of IsNumberValid
	 * @param context
	 * @param isnumbervalid
	 */
	public final void setIsNumberValid(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean isnumbervalid)
	{
		getMendixObject().setValue(context, MemberNames.IsNumberValid.toString(), isnumbervalid);
	}

	/**
	 * @return value of Box_Row
	 */
	public final rpoboxconfigurator.proxies.Row getBox_Row() throws com.mendix.core.CoreException
	{
		return getBox_Row(getContext());
	}

	/**
	 * @param context
	 * @return value of Box_Row
	 */
	public final rpoboxconfigurator.proxies.Row getBox_Row(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		rpoboxconfigurator.proxies.Row result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Box_Row.toString());
		if (identifier != null)
			result = rpoboxconfigurator.proxies.Row.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Box_Row
	 * @param box_row
	 */
	public final void setBox_Row(rpoboxconfigurator.proxies.Row box_row)
	{
		setBox_Row(getContext(), box_row);
	}

	/**
	 * Set value of Box_Row
	 * @param context
	 * @param box_row
	 */
	public final void setBox_Row(com.mendix.systemwideinterfaces.core.IContext context, rpoboxconfigurator.proxies.Row box_row)
	{
		if (box_row == null)
			getMendixObject().setValue(context, MemberNames.Box_Row.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Box_Row.toString(), box_row.getMendixObject().getId());
	}

	/**
	 * @return value of Box_Wall__Selected
	 */
	public final rpoboxconfigurator.proxies.Wall getBox_Wall__Selected() throws com.mendix.core.CoreException
	{
		return getBox_Wall__Selected(getContext());
	}

	/**
	 * @param context
	 * @return value of Box_Wall__Selected
	 */
	public final rpoboxconfigurator.proxies.Wall getBox_Wall__Selected(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		rpoboxconfigurator.proxies.Wall result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Box_Wall__Selected.toString());
		if (identifier != null)
			result = rpoboxconfigurator.proxies.Wall.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Box_Wall__Selected
	 * @param box_wall__selected
	 */
	public final void setBox_Wall__Selected(rpoboxconfigurator.proxies.Wall box_wall__selected)
	{
		setBox_Wall__Selected(getContext(), box_wall__selected);
	}

	/**
	 * Set value of Box_Wall__Selected
	 * @param context
	 * @param box_wall__selected
	 */
	public final void setBox_Wall__Selected(com.mendix.systemwideinterfaces.core.IContext context, rpoboxconfigurator.proxies.Wall box_wall__selected)
	{
		if (box_wall__selected == null)
			getMendixObject().setValue(context, MemberNames.Box_Wall__Selected.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Box_Wall__Selected.toString(), box_wall__selected.getMendixObject().getId());
	}

	/**
	 * @return value of WallView_Box__Selected
	 */
	public final rpoboxconfigurator.proxies.WallView getWallView_Box__Selected() throws com.mendix.core.CoreException
	{
		return getWallView_Box__Selected(getContext());
	}

	/**
	 * @param context
	 * @return value of WallView_Box__Selected
	 */
	public final rpoboxconfigurator.proxies.WallView getWallView_Box__Selected(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		rpoboxconfigurator.proxies.WallView result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.WallView_Box__Selected.toString());
		if (identifier != null)
			result = rpoboxconfigurator.proxies.WallView.load(context, identifier);
		return result;
	}

	/**
	 * Set value of WallView_Box__Selected
	 * @param wallview_box__selected
	 */
	public final void setWallView_Box__Selected(rpoboxconfigurator.proxies.WallView wallview_box__selected)
	{
		setWallView_Box__Selected(getContext(), wallview_box__selected);
	}

	/**
	 * Set value of WallView_Box__Selected
	 * @param context
	 * @param wallview_box__selected
	 */
	public final void setWallView_Box__Selected(com.mendix.systemwideinterfaces.core.IContext context, rpoboxconfigurator.proxies.WallView wallview_box__selected)
	{
		if (wallview_box__selected == null)
			getMendixObject().setValue(context, MemberNames.WallView_Box__Selected.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.WallView_Box__Selected.toString(), wallview_box__selected.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return boxMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final rpoboxconfigurator.proxies.Box that = (rpoboxconfigurator.proxies.Box) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "RPOBoxConfigurator.Box";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
