// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package rpoboxconfigurator.proxies;

public enum Provinces
{
	AB(new java.lang.String[][] { new java.lang.String[] { "en_US", "AB" } }),
	BC(new java.lang.String[][] { new java.lang.String[] { "en_US", "BC" } }),
	MB(new java.lang.String[][] { new java.lang.String[] { "en_US", "MB" } }),
	NB(new java.lang.String[][] { new java.lang.String[] { "en_US", "NB" } }),
	NL(new java.lang.String[][] { new java.lang.String[] { "en_US", "NL" } }),
	NS(new java.lang.String[][] { new java.lang.String[] { "en_US", "NS" } }),
	NT(new java.lang.String[][] { new java.lang.String[] { "en_US", "NT" } }),
	NU(new java.lang.String[][] { new java.lang.String[] { "en_US", "NU" } }),
	ON(new java.lang.String[][] { new java.lang.String[] { "en_US", "ON" } }),
	PE(new java.lang.String[][] { new java.lang.String[] { "en_US", "PE" } }),
	QC(new java.lang.String[][] { new java.lang.String[] { "en_US", "QC" } }),
	SK(new java.lang.String[][] { new java.lang.String[] { "en_US", "SK" } }),
	YT(new java.lang.String[][] { new java.lang.String[] { "en_US", "YT" } });

	private java.util.Map<java.lang.String, java.lang.String> captions;

	private Provinces(java.lang.String[][] captionStrings)
	{
		this.captions = new java.util.HashMap<java.lang.String, java.lang.String>();
		for (java.lang.String[] captionString : captionStrings)
			captions.put(captionString[0], captionString[1]);
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		if (captions.containsKey(languageCode))
			return captions.get(languageCode);
		return captions.get("en_US");
	}

	public java.lang.String getCaption()
	{
		return captions.get("en_US");
	}
}
