// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package rpoboxconfigurator.proxies;

public class Row
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject rowMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "RPOBoxConfigurator.Row";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		RowType("RowType"),
		Sequence("Sequence"),
		IsValid("IsValid"),
		Row_Bank("RPOBoxConfigurator.Row_Bank"),
		Row_Wall__Selected("RPOBoxConfigurator.Row_Wall__Selected"),
		WallView_Row__Selected("RPOBoxConfigurator.WallView_Row__Selected");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Row(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "RPOBoxConfigurator.Row"));
	}

	protected Row(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject rowMendixObject)
	{
		if (rowMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("RPOBoxConfigurator.Row", rowMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a RPOBoxConfigurator.Row");

		this.rowMendixObject = rowMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Row.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static rpoboxconfigurator.proxies.Row initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return rpoboxconfigurator.proxies.Row.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static rpoboxconfigurator.proxies.Row initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new rpoboxconfigurator.proxies.Row(context, mendixObject);
	}

	public static rpoboxconfigurator.proxies.Row load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return rpoboxconfigurator.proxies.Row.initialize(context, mendixObject);
	}

	public static java.util.List<rpoboxconfigurator.proxies.Row> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<rpoboxconfigurator.proxies.Row> result = new java.util.ArrayList<rpoboxconfigurator.proxies.Row>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//RPOBoxConfigurator.Row" + xpathConstraint))
			result.add(rpoboxconfigurator.proxies.Row.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * Set value of RowType
	 * @param rowtype
	 */
	public final rpoboxconfigurator.proxies.RowType getRowType()
	{
		return getRowType(getContext());
	}

	/**
	 * @param context
	 * @return value of RowType
	 */
	public final rpoboxconfigurator.proxies.RowType getRowType(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.RowType.toString());
		if (obj == null)
			return null;

		return rpoboxconfigurator.proxies.RowType.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of RowType
	 * @param rowtype
	 */
	public final void setRowType(rpoboxconfigurator.proxies.RowType rowtype)
	{
		setRowType(getContext(), rowtype);
	}

	/**
	 * Set value of RowType
	 * @param context
	 * @param rowtype
	 */
	public final void setRowType(com.mendix.systemwideinterfaces.core.IContext context, rpoboxconfigurator.proxies.RowType rowtype)
	{
		if (rowtype != null)
			getMendixObject().setValue(context, MemberNames.RowType.toString(), rowtype.toString());
		else
			getMendixObject().setValue(context, MemberNames.RowType.toString(), null);
	}

	/**
	 * @return value of Sequence
	 */
	public final java.lang.Integer getSequence()
	{
		return getSequence(getContext());
	}

	/**
	 * @param context
	 * @return value of Sequence
	 */
	public final java.lang.Integer getSequence(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Sequence.toString());
	}

	/**
	 * Set value of Sequence
	 * @param sequence
	 */
	public final void setSequence(java.lang.Integer sequence)
	{
		setSequence(getContext(), sequence);
	}

	/**
	 * Set value of Sequence
	 * @param context
	 * @param sequence
	 */
	public final void setSequence(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer sequence)
	{
		getMendixObject().setValue(context, MemberNames.Sequence.toString(), sequence);
	}

	/**
	 * @return value of IsValid
	 */
	public final java.lang.Boolean getIsValid()
	{
		return getIsValid(getContext());
	}

	/**
	 * @param context
	 * @return value of IsValid
	 */
	public final java.lang.Boolean getIsValid(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.IsValid.toString());
	}

	/**
	 * Set value of IsValid
	 * @param isvalid
	 */
	public final void setIsValid(java.lang.Boolean isvalid)
	{
		setIsValid(getContext(), isvalid);
	}

	/**
	 * Set value of IsValid
	 * @param context
	 * @param isvalid
	 */
	public final void setIsValid(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean isvalid)
	{
		getMendixObject().setValue(context, MemberNames.IsValid.toString(), isvalid);
	}

	/**
	 * @return value of Row_Bank
	 */
	public final rpoboxconfigurator.proxies.Bank getRow_Bank() throws com.mendix.core.CoreException
	{
		return getRow_Bank(getContext());
	}

	/**
	 * @param context
	 * @return value of Row_Bank
	 */
	public final rpoboxconfigurator.proxies.Bank getRow_Bank(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		rpoboxconfigurator.proxies.Bank result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Row_Bank.toString());
		if (identifier != null)
			result = rpoboxconfigurator.proxies.Bank.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Row_Bank
	 * @param row_bank
	 */
	public final void setRow_Bank(rpoboxconfigurator.proxies.Bank row_bank)
	{
		setRow_Bank(getContext(), row_bank);
	}

	/**
	 * Set value of Row_Bank
	 * @param context
	 * @param row_bank
	 */
	public final void setRow_Bank(com.mendix.systemwideinterfaces.core.IContext context, rpoboxconfigurator.proxies.Bank row_bank)
	{
		if (row_bank == null)
			getMendixObject().setValue(context, MemberNames.Row_Bank.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Row_Bank.toString(), row_bank.getMendixObject().getId());
	}

	/**
	 * @return value of Row_Wall__Selected
	 */
	public final rpoboxconfigurator.proxies.Wall getRow_Wall__Selected() throws com.mendix.core.CoreException
	{
		return getRow_Wall__Selected(getContext());
	}

	/**
	 * @param context
	 * @return value of Row_Wall__Selected
	 */
	public final rpoboxconfigurator.proxies.Wall getRow_Wall__Selected(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		rpoboxconfigurator.proxies.Wall result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Row_Wall__Selected.toString());
		if (identifier != null)
			result = rpoboxconfigurator.proxies.Wall.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Row_Wall__Selected
	 * @param row_wall__selected
	 */
	public final void setRow_Wall__Selected(rpoboxconfigurator.proxies.Wall row_wall__selected)
	{
		setRow_Wall__Selected(getContext(), row_wall__selected);
	}

	/**
	 * Set value of Row_Wall__Selected
	 * @param context
	 * @param row_wall__selected
	 */
	public final void setRow_Wall__Selected(com.mendix.systemwideinterfaces.core.IContext context, rpoboxconfigurator.proxies.Wall row_wall__selected)
	{
		if (row_wall__selected == null)
			getMendixObject().setValue(context, MemberNames.Row_Wall__Selected.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Row_Wall__Selected.toString(), row_wall__selected.getMendixObject().getId());
	}

	/**
	 * @return value of WallView_Row__Selected
	 */
	public final rpoboxconfigurator.proxies.WallView getWallView_Row__Selected() throws com.mendix.core.CoreException
	{
		return getWallView_Row__Selected(getContext());
	}

	/**
	 * @param context
	 * @return value of WallView_Row__Selected
	 */
	public final rpoboxconfigurator.proxies.WallView getWallView_Row__Selected(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		rpoboxconfigurator.proxies.WallView result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.WallView_Row__Selected.toString());
		if (identifier != null)
			result = rpoboxconfigurator.proxies.WallView.load(context, identifier);
		return result;
	}

	/**
	 * Set value of WallView_Row__Selected
	 * @param wallview_row__selected
	 */
	public final void setWallView_Row__Selected(rpoboxconfigurator.proxies.WallView wallview_row__selected)
	{
		setWallView_Row__Selected(getContext(), wallview_row__selected);
	}

	/**
	 * Set value of WallView_Row__Selected
	 * @param context
	 * @param wallview_row__selected
	 */
	public final void setWallView_Row__Selected(com.mendix.systemwideinterfaces.core.IContext context, rpoboxconfigurator.proxies.WallView wallview_row__selected)
	{
		if (wallview_row__selected == null)
			getMendixObject().setValue(context, MemberNames.WallView_Row__Selected.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.WallView_Row__Selected.toString(), wallview_row__selected.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return rowMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final rpoboxconfigurator.proxies.Row that = (rpoboxconfigurator.proxies.Row) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "RPOBoxConfigurator.Row";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
