// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package rpoboxconfigurator.proxies;

public enum RowType
{
	A(new java.lang.String[][] { new java.lang.String[] { "en_US", "A" } }),
	B(new java.lang.String[][] { new java.lang.String[] { "en_US", "B" } }),
	C(new java.lang.String[][] { new java.lang.String[] { "en_US", "C" } }),
	D(new java.lang.String[][] { new java.lang.String[] { "en_US", "D" } }),
	E(new java.lang.String[][] { new java.lang.String[] { "en_US", "E" } }),
	E2(new java.lang.String[][] { new java.lang.String[] { "en_US", "E2" } });

	private java.util.Map<java.lang.String, java.lang.String> captions;

	private RowType(java.lang.String[][] captionStrings)
	{
		this.captions = new java.util.HashMap<java.lang.String, java.lang.String>();
		for (java.lang.String[] captionString : captionStrings)
			captions.put(captionString[0], captionString[1]);
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		if (captions.containsKey(languageCode))
			return captions.get(languageCode);
		return captions.get("en_US");
	}

	public java.lang.String getCaption()
	{
		return captions.get("en_US");
	}
}
