// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package rpoboxconfigurator.proxies;

public class RPO
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject rPOMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "RPOBoxConfigurator.RPO";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Number("Number"),
		Name("Name"),
		BusinessName("BusinessName"),
		Address("Address"),
		Province("Province"),
		PostalCode("PostalCode"),
		Phone("Phone"),
		SearchString("SearchString"),
		Status("Status"),
		CompletedDate("CompletedDate"),
		LastModifiedDate("LastModifiedDate");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public RPO(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "RPOBoxConfigurator.RPO"));
	}

	protected RPO(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject rPOMendixObject)
	{
		if (rPOMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("RPOBoxConfigurator.RPO", rPOMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a RPOBoxConfigurator.RPO");

		this.rPOMendixObject = rPOMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'RPO.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static rpoboxconfigurator.proxies.RPO initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return rpoboxconfigurator.proxies.RPO.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static rpoboxconfigurator.proxies.RPO initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new rpoboxconfigurator.proxies.RPO(context, mendixObject);
	}

	public static rpoboxconfigurator.proxies.RPO load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return rpoboxconfigurator.proxies.RPO.initialize(context, mendixObject);
	}

	public static java.util.List<rpoboxconfigurator.proxies.RPO> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<rpoboxconfigurator.proxies.RPO> result = new java.util.ArrayList<rpoboxconfigurator.proxies.RPO>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//RPOBoxConfigurator.RPO" + xpathConstraint))
			result.add(rpoboxconfigurator.proxies.RPO.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Number
	 */
	public final java.lang.Integer getNumber()
	{
		return getNumber(getContext());
	}

	/**
	 * @param context
	 * @return value of Number
	 */
	public final java.lang.Integer getNumber(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Number.toString());
	}

	/**
	 * Set value of Number
	 * @param number
	 */
	public final void setNumber(java.lang.Integer number)
	{
		setNumber(getContext(), number);
	}

	/**
	 * Set value of Number
	 * @param context
	 * @param number
	 */
	public final void setNumber(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer number)
	{
		getMendixObject().setValue(context, MemberNames.Number.toString(), number);
	}

	/**
	 * @return value of Name
	 */
	public final java.lang.String getName()
	{
		return getName(getContext());
	}

	/**
	 * @param context
	 * @return value of Name
	 */
	public final java.lang.String getName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Name.toString());
	}

	/**
	 * Set value of Name
	 * @param name
	 */
	public final void setName(java.lang.String name)
	{
		setName(getContext(), name);
	}

	/**
	 * Set value of Name
	 * @param context
	 * @param name
	 */
	public final void setName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String name)
	{
		getMendixObject().setValue(context, MemberNames.Name.toString(), name);
	}

	/**
	 * @return value of BusinessName
	 */
	public final java.lang.String getBusinessName()
	{
		return getBusinessName(getContext());
	}

	/**
	 * @param context
	 * @return value of BusinessName
	 */
	public final java.lang.String getBusinessName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.BusinessName.toString());
	}

	/**
	 * Set value of BusinessName
	 * @param businessname
	 */
	public final void setBusinessName(java.lang.String businessname)
	{
		setBusinessName(getContext(), businessname);
	}

	/**
	 * Set value of BusinessName
	 * @param context
	 * @param businessname
	 */
	public final void setBusinessName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String businessname)
	{
		getMendixObject().setValue(context, MemberNames.BusinessName.toString(), businessname);
	}

	/**
	 * @return value of Address
	 */
	public final java.lang.String getAddress()
	{
		return getAddress(getContext());
	}

	/**
	 * @param context
	 * @return value of Address
	 */
	public final java.lang.String getAddress(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Address.toString());
	}

	/**
	 * Set value of Address
	 * @param address
	 */
	public final void setAddress(java.lang.String address)
	{
		setAddress(getContext(), address);
	}

	/**
	 * Set value of Address
	 * @param context
	 * @param address
	 */
	public final void setAddress(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String address)
	{
		getMendixObject().setValue(context, MemberNames.Address.toString(), address);
	}

	/**
	 * Set value of Province
	 * @param province
	 */
	public final rpoboxconfigurator.proxies.Provinces getProvince()
	{
		return getProvince(getContext());
	}

	/**
	 * @param context
	 * @return value of Province
	 */
	public final rpoboxconfigurator.proxies.Provinces getProvince(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.Province.toString());
		if (obj == null)
			return null;

		return rpoboxconfigurator.proxies.Provinces.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of Province
	 * @param province
	 */
	public final void setProvince(rpoboxconfigurator.proxies.Provinces province)
	{
		setProvince(getContext(), province);
	}

	/**
	 * Set value of Province
	 * @param context
	 * @param province
	 */
	public final void setProvince(com.mendix.systemwideinterfaces.core.IContext context, rpoboxconfigurator.proxies.Provinces province)
	{
		if (province != null)
			getMendixObject().setValue(context, MemberNames.Province.toString(), province.toString());
		else
			getMendixObject().setValue(context, MemberNames.Province.toString(), null);
	}

	/**
	 * @return value of PostalCode
	 */
	public final java.lang.String getPostalCode()
	{
		return getPostalCode(getContext());
	}

	/**
	 * @param context
	 * @return value of PostalCode
	 */
	public final java.lang.String getPostalCode(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.PostalCode.toString());
	}

	/**
	 * Set value of PostalCode
	 * @param postalcode
	 */
	public final void setPostalCode(java.lang.String postalcode)
	{
		setPostalCode(getContext(), postalcode);
	}

	/**
	 * Set value of PostalCode
	 * @param context
	 * @param postalcode
	 */
	public final void setPostalCode(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String postalcode)
	{
		getMendixObject().setValue(context, MemberNames.PostalCode.toString(), postalcode);
	}

	/**
	 * @return value of Phone
	 */
	public final java.lang.String getPhone()
	{
		return getPhone(getContext());
	}

	/**
	 * @param context
	 * @return value of Phone
	 */
	public final java.lang.String getPhone(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Phone.toString());
	}

	/**
	 * Set value of Phone
	 * @param phone
	 */
	public final void setPhone(java.lang.String phone)
	{
		setPhone(getContext(), phone);
	}

	/**
	 * Set value of Phone
	 * @param context
	 * @param phone
	 */
	public final void setPhone(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String phone)
	{
		getMendixObject().setValue(context, MemberNames.Phone.toString(), phone);
	}

	/**
	 * @return value of SearchString
	 */
	public final java.lang.String getSearchString()
	{
		return getSearchString(getContext());
	}

	/**
	 * @param context
	 * @return value of SearchString
	 */
	public final java.lang.String getSearchString(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.SearchString.toString());
	}

	/**
	 * Set value of SearchString
	 * @param searchstring
	 */
	public final void setSearchString(java.lang.String searchstring)
	{
		setSearchString(getContext(), searchstring);
	}

	/**
	 * Set value of SearchString
	 * @param context
	 * @param searchstring
	 */
	public final void setSearchString(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String searchstring)
	{
		getMendixObject().setValue(context, MemberNames.SearchString.toString(), searchstring);
	}

	/**
	 * Set value of Status
	 * @param status
	 */
	public final rpoboxconfigurator.proxies.CompletedStatus getStatus()
	{
		return getStatus(getContext());
	}

	/**
	 * @param context
	 * @return value of Status
	 */
	public final rpoboxconfigurator.proxies.CompletedStatus getStatus(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.Status.toString());
		if (obj == null)
			return null;

		return rpoboxconfigurator.proxies.CompletedStatus.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of Status
	 * @param status
	 */
	public final void setStatus(rpoboxconfigurator.proxies.CompletedStatus status)
	{
		setStatus(getContext(), status);
	}

	/**
	 * Set value of Status
	 * @param context
	 * @param status
	 */
	public final void setStatus(com.mendix.systemwideinterfaces.core.IContext context, rpoboxconfigurator.proxies.CompletedStatus status)
	{
		if (status != null)
			getMendixObject().setValue(context, MemberNames.Status.toString(), status.toString());
		else
			getMendixObject().setValue(context, MemberNames.Status.toString(), null);
	}

	/**
	 * @return value of CompletedDate
	 */
	public final java.util.Date getCompletedDate()
	{
		return getCompletedDate(getContext());
	}

	/**
	 * @param context
	 * @return value of CompletedDate
	 */
	public final java.util.Date getCompletedDate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.CompletedDate.toString());
	}

	/**
	 * Set value of CompletedDate
	 * @param completeddate
	 */
	public final void setCompletedDate(java.util.Date completeddate)
	{
		setCompletedDate(getContext(), completeddate);
	}

	/**
	 * Set value of CompletedDate
	 * @param context
	 * @param completeddate
	 */
	public final void setCompletedDate(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date completeddate)
	{
		getMendixObject().setValue(context, MemberNames.CompletedDate.toString(), completeddate);
	}

	/**
	 * @return value of LastModifiedDate
	 */
	public final java.util.Date getLastModifiedDate()
	{
		return getLastModifiedDate(getContext());
	}

	/**
	 * @param context
	 * @return value of LastModifiedDate
	 */
	public final java.util.Date getLastModifiedDate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.LastModifiedDate.toString());
	}

	/**
	 * Set value of LastModifiedDate
	 * @param lastmodifieddate
	 */
	public final void setLastModifiedDate(java.util.Date lastmodifieddate)
	{
		setLastModifiedDate(getContext(), lastmodifieddate);
	}

	/**
	 * Set value of LastModifiedDate
	 * @param context
	 * @param lastmodifieddate
	 */
	public final void setLastModifiedDate(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date lastmodifieddate)
	{
		getMendixObject().setValue(context, MemberNames.LastModifiedDate.toString(), lastmodifieddate);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return rPOMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final rpoboxconfigurator.proxies.RPO that = (rpoboxconfigurator.proxies.RPO) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "RPOBoxConfigurator.RPO";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
