// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package rpoboxconfigurator.proxies;

public class Wall
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject wallMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "RPOBoxConfigurator.Wall";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Name("Name"),
		CompletedStatus("CompletedStatus"),
		LastModifiedDate("LastModifiedDate"),
		Box_Wall__Selected("RPOBoxConfigurator.Box_Wall__Selected"),
		Row_Wall__Selected("RPOBoxConfigurator.Row_Wall__Selected"),
		Wall_RPO("RPOBoxConfigurator.Wall_RPO");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Wall(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "RPOBoxConfigurator.Wall"));
	}

	protected Wall(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject wallMendixObject)
	{
		if (wallMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("RPOBoxConfigurator.Wall", wallMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a RPOBoxConfigurator.Wall");

		this.wallMendixObject = wallMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Wall.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static rpoboxconfigurator.proxies.Wall initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return rpoboxconfigurator.proxies.Wall.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static rpoboxconfigurator.proxies.Wall initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new rpoboxconfigurator.proxies.Wall(context, mendixObject);
	}

	public static rpoboxconfigurator.proxies.Wall load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return rpoboxconfigurator.proxies.Wall.initialize(context, mendixObject);
	}

	public static java.util.List<rpoboxconfigurator.proxies.Wall> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<rpoboxconfigurator.proxies.Wall> result = new java.util.ArrayList<rpoboxconfigurator.proxies.Wall>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//RPOBoxConfigurator.Wall" + xpathConstraint))
			result.add(rpoboxconfigurator.proxies.Wall.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Name
	 */
	public final java.lang.String getName()
	{
		return getName(getContext());
	}

	/**
	 * @param context
	 * @return value of Name
	 */
	public final java.lang.String getName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Name.toString());
	}

	/**
	 * Set value of Name
	 * @param name
	 */
	public final void setName(java.lang.String name)
	{
		setName(getContext(), name);
	}

	/**
	 * Set value of Name
	 * @param context
	 * @param name
	 */
	public final void setName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String name)
	{
		getMendixObject().setValue(context, MemberNames.Name.toString(), name);
	}

	/**
	 * Set value of CompletedStatus
	 * @param completedstatus
	 */
	public final rpoboxconfigurator.proxies.CompletedStatus getCompletedStatus()
	{
		return getCompletedStatus(getContext());
	}

	/**
	 * @param context
	 * @return value of CompletedStatus
	 */
	public final rpoboxconfigurator.proxies.CompletedStatus getCompletedStatus(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.CompletedStatus.toString());
		if (obj == null)
			return null;

		return rpoboxconfigurator.proxies.CompletedStatus.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of CompletedStatus
	 * @param completedstatus
	 */
	public final void setCompletedStatus(rpoboxconfigurator.proxies.CompletedStatus completedstatus)
	{
		setCompletedStatus(getContext(), completedstatus);
	}

	/**
	 * Set value of CompletedStatus
	 * @param context
	 * @param completedstatus
	 */
	public final void setCompletedStatus(com.mendix.systemwideinterfaces.core.IContext context, rpoboxconfigurator.proxies.CompletedStatus completedstatus)
	{
		if (completedstatus != null)
			getMendixObject().setValue(context, MemberNames.CompletedStatus.toString(), completedstatus.toString());
		else
			getMendixObject().setValue(context, MemberNames.CompletedStatus.toString(), null);
	}

	/**
	 * @return value of LastModifiedDate
	 */
	public final java.util.Date getLastModifiedDate()
	{
		return getLastModifiedDate(getContext());
	}

	/**
	 * @param context
	 * @return value of LastModifiedDate
	 */
	public final java.util.Date getLastModifiedDate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.LastModifiedDate.toString());
	}

	/**
	 * Set value of LastModifiedDate
	 * @param lastmodifieddate
	 */
	public final void setLastModifiedDate(java.util.Date lastmodifieddate)
	{
		setLastModifiedDate(getContext(), lastmodifieddate);
	}

	/**
	 * Set value of LastModifiedDate
	 * @param context
	 * @param lastmodifieddate
	 */
	public final void setLastModifiedDate(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date lastmodifieddate)
	{
		getMendixObject().setValue(context, MemberNames.LastModifiedDate.toString(), lastmodifieddate);
	}

	/**
	 * @return value of Box_Wall__Selected
	 */
	public final rpoboxconfigurator.proxies.Box getBox_Wall__Selected() throws com.mendix.core.CoreException
	{
		return getBox_Wall__Selected(getContext());
	}

	/**
	 * @param context
	 * @return value of Box_Wall__Selected
	 */
	public final rpoboxconfigurator.proxies.Box getBox_Wall__Selected(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		rpoboxconfigurator.proxies.Box result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Box_Wall__Selected.toString());
		if (identifier != null)
			result = rpoboxconfigurator.proxies.Box.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Box_Wall__Selected
	 * @param box_wall__selected
	 */
	public final void setBox_Wall__Selected(rpoboxconfigurator.proxies.Box box_wall__selected)
	{
		setBox_Wall__Selected(getContext(), box_wall__selected);
	}

	/**
	 * Set value of Box_Wall__Selected
	 * @param context
	 * @param box_wall__selected
	 */
	public final void setBox_Wall__Selected(com.mendix.systemwideinterfaces.core.IContext context, rpoboxconfigurator.proxies.Box box_wall__selected)
	{
		if (box_wall__selected == null)
			getMendixObject().setValue(context, MemberNames.Box_Wall__Selected.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Box_Wall__Selected.toString(), box_wall__selected.getMendixObject().getId());
	}

	/**
	 * @return value of Row_Wall__Selected
	 */
	public final rpoboxconfigurator.proxies.Row getRow_Wall__Selected() throws com.mendix.core.CoreException
	{
		return getRow_Wall__Selected(getContext());
	}

	/**
	 * @param context
	 * @return value of Row_Wall__Selected
	 */
	public final rpoboxconfigurator.proxies.Row getRow_Wall__Selected(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		rpoboxconfigurator.proxies.Row result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Row_Wall__Selected.toString());
		if (identifier != null)
			result = rpoboxconfigurator.proxies.Row.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Row_Wall__Selected
	 * @param row_wall__selected
	 */
	public final void setRow_Wall__Selected(rpoboxconfigurator.proxies.Row row_wall__selected)
	{
		setRow_Wall__Selected(getContext(), row_wall__selected);
	}

	/**
	 * Set value of Row_Wall__Selected
	 * @param context
	 * @param row_wall__selected
	 */
	public final void setRow_Wall__Selected(com.mendix.systemwideinterfaces.core.IContext context, rpoboxconfigurator.proxies.Row row_wall__selected)
	{
		if (row_wall__selected == null)
			getMendixObject().setValue(context, MemberNames.Row_Wall__Selected.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Row_Wall__Selected.toString(), row_wall__selected.getMendixObject().getId());
	}

	/**
	 * @return value of Wall_RPO
	 */
	public final rpoboxconfigurator.proxies.RPO getWall_RPO() throws com.mendix.core.CoreException
	{
		return getWall_RPO(getContext());
	}

	/**
	 * @param context
	 * @return value of Wall_RPO
	 */
	public final rpoboxconfigurator.proxies.RPO getWall_RPO(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		rpoboxconfigurator.proxies.RPO result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Wall_RPO.toString());
		if (identifier != null)
			result = rpoboxconfigurator.proxies.RPO.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Wall_RPO
	 * @param wall_rpo
	 */
	public final void setWall_RPO(rpoboxconfigurator.proxies.RPO wall_rpo)
	{
		setWall_RPO(getContext(), wall_rpo);
	}

	/**
	 * Set value of Wall_RPO
	 * @param context
	 * @param wall_rpo
	 */
	public final void setWall_RPO(com.mendix.systemwideinterfaces.core.IContext context, rpoboxconfigurator.proxies.RPO wall_rpo)
	{
		if (wall_rpo == null)
			getMendixObject().setValue(context, MemberNames.Wall_RPO.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Wall_RPO.toString(), wall_rpo.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return wallMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final rpoboxconfigurator.proxies.Wall that = (rpoboxconfigurator.proxies.Wall) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "RPOBoxConfigurator.Wall";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
