// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package rpoboxconfigurator.proxies;

public class WallView
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject wallViewMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "RPOBoxConfigurator.WallView";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Offset("Offset"),
		Length("Length"),
		WallView_Wall("RPOBoxConfigurator.WallView_Wall"),
		WallView_Bank("RPOBoxConfigurator.WallView_Bank"),
		WallView_Row__Selected("RPOBoxConfigurator.WallView_Row__Selected"),
		WallView_Box__Selected("RPOBoxConfigurator.WallView_Box__Selected"),
		WallView_User("RPOBoxConfigurator.WallView_User");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public WallView(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "RPOBoxConfigurator.WallView"));
	}

	protected WallView(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject wallViewMendixObject)
	{
		if (wallViewMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("RPOBoxConfigurator.WallView", wallViewMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a RPOBoxConfigurator.WallView");

		this.wallViewMendixObject = wallViewMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'WallView.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static rpoboxconfigurator.proxies.WallView initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return rpoboxconfigurator.proxies.WallView.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static rpoboxconfigurator.proxies.WallView initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new rpoboxconfigurator.proxies.WallView(context, mendixObject);
	}

	public static rpoboxconfigurator.proxies.WallView load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return rpoboxconfigurator.proxies.WallView.initialize(context, mendixObject);
	}

	public static java.util.List<rpoboxconfigurator.proxies.WallView> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<rpoboxconfigurator.proxies.WallView> result = new java.util.ArrayList<rpoboxconfigurator.proxies.WallView>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//RPOBoxConfigurator.WallView" + xpathConstraint))
			result.add(rpoboxconfigurator.proxies.WallView.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Offset
	 */
	public final java.lang.Integer getOffset()
	{
		return getOffset(getContext());
	}

	/**
	 * @param context
	 * @return value of Offset
	 */
	public final java.lang.Integer getOffset(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Offset.toString());
	}

	/**
	 * Set value of Offset
	 * @param offset
	 */
	public final void setOffset(java.lang.Integer offset)
	{
		setOffset(getContext(), offset);
	}

	/**
	 * Set value of Offset
	 * @param context
	 * @param offset
	 */
	public final void setOffset(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer offset)
	{
		getMendixObject().setValue(context, MemberNames.Offset.toString(), offset);
	}

	/**
	 * @return value of Length
	 */
	public final java.lang.Integer getLength()
	{
		return getLength(getContext());
	}

	/**
	 * @param context
	 * @return value of Length
	 */
	public final java.lang.Integer getLength(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Length.toString());
	}

	/**
	 * Set value of Length
	 * @param length
	 */
	public final void setLength(java.lang.Integer length)
	{
		setLength(getContext(), length);
	}

	/**
	 * Set value of Length
	 * @param context
	 * @param length
	 */
	public final void setLength(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer length)
	{
		getMendixObject().setValue(context, MemberNames.Length.toString(), length);
	}

	/**
	 * @return value of WallView_Wall
	 */
	public final rpoboxconfigurator.proxies.Wall getWallView_Wall() throws com.mendix.core.CoreException
	{
		return getWallView_Wall(getContext());
	}

	/**
	 * @param context
	 * @return value of WallView_Wall
	 */
	public final rpoboxconfigurator.proxies.Wall getWallView_Wall(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		rpoboxconfigurator.proxies.Wall result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.WallView_Wall.toString());
		if (identifier != null)
			result = rpoboxconfigurator.proxies.Wall.load(context, identifier);
		return result;
	}

	/**
	 * Set value of WallView_Wall
	 * @param wallview_wall
	 */
	public final void setWallView_Wall(rpoboxconfigurator.proxies.Wall wallview_wall)
	{
		setWallView_Wall(getContext(), wallview_wall);
	}

	/**
	 * Set value of WallView_Wall
	 * @param context
	 * @param wallview_wall
	 */
	public final void setWallView_Wall(com.mendix.systemwideinterfaces.core.IContext context, rpoboxconfigurator.proxies.Wall wallview_wall)
	{
		if (wallview_wall == null)
			getMendixObject().setValue(context, MemberNames.WallView_Wall.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.WallView_Wall.toString(), wallview_wall.getMendixObject().getId());
	}

	/**
	 * @return value of WallView_Bank
	 */
	public final java.util.List<rpoboxconfigurator.proxies.Bank> getWallView_Bank() throws com.mendix.core.CoreException
	{
		return getWallView_Bank(getContext());
	}

	/**
	 * @param context
	 * @return value of WallView_Bank
	 */
	@SuppressWarnings("unchecked")
	public final java.util.List<rpoboxconfigurator.proxies.Bank> getWallView_Bank(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		java.util.List<rpoboxconfigurator.proxies.Bank> result = new java.util.ArrayList<rpoboxconfigurator.proxies.Bank>();
		Object valueObject = getMendixObject().getValue(context, MemberNames.WallView_Bank.toString());
		if (valueObject == null)
			return result;
		for (com.mendix.systemwideinterfaces.core.IMendixObject mendixObject : com.mendix.core.Core.retrieveIdList(context, (java.util.List<com.mendix.systemwideinterfaces.core.IMendixIdentifier>) valueObject))
			result.add(rpoboxconfigurator.proxies.Bank.initialize(context, mendixObject));
		return result;
	}

	/**
	 * Set value of WallView_Bank
	 * @param wallview_bank
	 */
	public final void setWallView_Bank(java.util.List<rpoboxconfigurator.proxies.Bank> wallview_bank)
	{
		setWallView_Bank(getContext(), wallview_bank);
	}

	/**
	 * Set value of WallView_Bank
	 * @param context
	 * @param wallview_bank
	 */
	public final void setWallView_Bank(com.mendix.systemwideinterfaces.core.IContext context, java.util.List<rpoboxconfigurator.proxies.Bank> wallview_bank)
	{
		java.util.List<com.mendix.systemwideinterfaces.core.IMendixIdentifier> identifiers = new java.util.ArrayList<com.mendix.systemwideinterfaces.core.IMendixIdentifier>();
		for (rpoboxconfigurator.proxies.Bank proxyObject : wallview_bank)
			identifiers.add(proxyObject.getMendixObject().getId());
		getMendixObject().setValue(context, MemberNames.WallView_Bank.toString(), identifiers);
	}

	/**
	 * @return value of WallView_Row__Selected
	 */
	public final rpoboxconfigurator.proxies.Row getWallView_Row__Selected() throws com.mendix.core.CoreException
	{
		return getWallView_Row__Selected(getContext());
	}

	/**
	 * @param context
	 * @return value of WallView_Row__Selected
	 */
	public final rpoboxconfigurator.proxies.Row getWallView_Row__Selected(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		rpoboxconfigurator.proxies.Row result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.WallView_Row__Selected.toString());
		if (identifier != null)
			result = rpoboxconfigurator.proxies.Row.load(context, identifier);
		return result;
	}

	/**
	 * Set value of WallView_Row__Selected
	 * @param wallview_row__selected
	 */
	public final void setWallView_Row__Selected(rpoboxconfigurator.proxies.Row wallview_row__selected)
	{
		setWallView_Row__Selected(getContext(), wallview_row__selected);
	}

	/**
	 * Set value of WallView_Row__Selected
	 * @param context
	 * @param wallview_row__selected
	 */
	public final void setWallView_Row__Selected(com.mendix.systemwideinterfaces.core.IContext context, rpoboxconfigurator.proxies.Row wallview_row__selected)
	{
		if (wallview_row__selected == null)
			getMendixObject().setValue(context, MemberNames.WallView_Row__Selected.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.WallView_Row__Selected.toString(), wallview_row__selected.getMendixObject().getId());
	}

	/**
	 * @return value of WallView_Box__Selected
	 */
	public final rpoboxconfigurator.proxies.Box getWallView_Box__Selected() throws com.mendix.core.CoreException
	{
		return getWallView_Box__Selected(getContext());
	}

	/**
	 * @param context
	 * @return value of WallView_Box__Selected
	 */
	public final rpoboxconfigurator.proxies.Box getWallView_Box__Selected(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		rpoboxconfigurator.proxies.Box result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.WallView_Box__Selected.toString());
		if (identifier != null)
			result = rpoboxconfigurator.proxies.Box.load(context, identifier);
		return result;
	}

	/**
	 * Set value of WallView_Box__Selected
	 * @param wallview_box__selected
	 */
	public final void setWallView_Box__Selected(rpoboxconfigurator.proxies.Box wallview_box__selected)
	{
		setWallView_Box__Selected(getContext(), wallview_box__selected);
	}

	/**
	 * Set value of WallView_Box__Selected
	 * @param context
	 * @param wallview_box__selected
	 */
	public final void setWallView_Box__Selected(com.mendix.systemwideinterfaces.core.IContext context, rpoboxconfigurator.proxies.Box wallview_box__selected)
	{
		if (wallview_box__selected == null)
			getMendixObject().setValue(context, MemberNames.WallView_Box__Selected.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.WallView_Box__Selected.toString(), wallview_box__selected.getMendixObject().getId());
	}

	/**
	 * @return value of WallView_User
	 */
	public final system.proxies.User getWallView_User() throws com.mendix.core.CoreException
	{
		return getWallView_User(getContext());
	}

	/**
	 * @param context
	 * @return value of WallView_User
	 */
	public final system.proxies.User getWallView_User(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		system.proxies.User result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.WallView_User.toString());
		if (identifier != null)
			result = system.proxies.User.load(context, identifier);
		return result;
	}

	/**
	 * Set value of WallView_User
	 * @param wallview_user
	 */
	public final void setWallView_User(system.proxies.User wallview_user)
	{
		setWallView_User(getContext(), wallview_user);
	}

	/**
	 * Set value of WallView_User
	 * @param context
	 * @param wallview_user
	 */
	public final void setWallView_User(com.mendix.systemwideinterfaces.core.IContext context, system.proxies.User wallview_user)
	{
		if (wallview_user == null)
			getMendixObject().setValue(context, MemberNames.WallView_User.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.WallView_User.toString(), wallview_user.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return wallViewMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final rpoboxconfigurator.proxies.WallView that = (rpoboxconfigurator.proxies.WallView) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "RPOBoxConfigurator.WallView";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
