// This file was generated by Mendix Modeler 7.16.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package rpoboxconfigurator.proxies.constants;

import com.mendix.core.Core;

public class Constants
{
	// These are the constants for the RPOBoxConfigurator module

	public static java.lang.String getLogNodeName()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("RPOBoxConfigurator.LogNodeName");
	}

	public static boolean getUseKeyboard()
	{
		return (java.lang.Boolean)Core.getConfiguration().getConstantValue("RPOBoxConfigurator.UseKeyboard");
	}
}